### ISSUE TITLE
[FEATURE] Shop employee

### ISSUE THREAD

**Issue by qbtl** [ClickNToulon/clickntoulon-laravel#25]
## Proposed feature
This feature focuses on adding a shop employee system. This aims to help store owners delegate and control employees authorizations. The goal is to have a system that separates the store account and employees accounts via a authorizations-controled system.

## Task list
- [ ] Add new Employee model
- [ ] Update routes
- [ ] Create new Employee Policy
- [ ] Implement policy-based methods to check if user is an employee of a particular store
- [ ] Update UI, error messages
