### ISSUE TITLE
[FEATURE] Shop ban

### ISSUE THREAD

**Issue by qbtl** [ClickNToulon/clickntoulon-laravel#26]
## Proposed feature
This feature adds a shop banning system. We should be able to ban a shop that does not respect our terms and conditions.

## Task list
- [ ] Add the controller method using DELETE method
- [ ] Update UI
- [ ] Add ban animations
- [ ] Add unban methods and UI
