### ISSUE TITLE
[FEATURE] Report Product

### ISSUE THREAD

**Issue by qbtl** [ClickNToulon/clickntoulon-laravel#29]
## Proposed feature
This feature adds product moderation. We need to make sure the products are respecting the terms and conditions, are not sold to childrens under age. This ensures we are able to moderate fake products and dangerous products

## Task list
- [ ] Add the Report model
- [ ] Add the controller and route
- [ ] Add the Form UI
